version: "3"

services:
  fpm_test:
    build:
      context: .
      dockerfile: Dockerfile-php
    networks:
     - symfony

  db:
    image: mariadb:10
    environment:
    - MYSQL_ROOT_PASSWORD=root
    networks:
    - symfony

networks:
 symfony:
